In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
%matplotlib inline 
import matplotlib.pyplot as plt

In [2]:
cell_df = pd.read_csv("ReplicatedAcousticFeatures-ParkinsonDatabase (1).csv")
cell_df.head()

ID  Recording  Status  Gender  Pitch Local  Shim Loc  Amplitude  \
0  CONT-01          1       0       1     0.064654  0.030256   0.070478   
1  CONT-01          2       0       1     0.093459  0.023146   0.053850   
2  CONT-01          3       0       1     0.059513  0.019338   0.044642   
3  CONT-02          1       0       0     0.073942  0.024716   0.056437   
4  CONT-02          2       0       0     0.058310  0.013119   0.031014   

    Harmonic      RPDE       DFA       PPE       GNE      MFCC     Delta  
0  69.444370  0.250433  0.599346  0.005397  0.900404  1.318551  1.404508  
1  71.426435  0.271445  0.581242  0.075617  0.887042  1.284004  1.318490  
2  70.156291  0.203531  0.600759  0.005283  0.889399  1.338276  1.354933  
3  75.863575  0.261360  0.625216  0.030518  0.875984  1.555013  1.484138  
4  82.083492  0.222069  0.602493  0.035602  0.902206  1.468737  1.492090

In [10]:
feature_df = cell_df[['Recording', 'Gender', 'Pitch Local', 'Shim Loc',
       'Amplitude', 'Harmonic', 'RPDE', 'DFA', 'PPE', 'GNE', 'MFCC', 'Delta']]
X = np.asarray(feature_df)
X[0:5]

array([[1.00000000e+00, 1.00000000e+00, 6.46537450e-02, 3.02560000e-02,
        7.04782000e-02, 6.94443700e+01, 2.50432662e-01, 5.99346197e-01,
        5.39662400e-03, 9.00403826e-01, 1.31855079e+00, 1.40450769e+00],
       [2.00000000e+00, 1.00000000e+00, 9.34594910e-02, 2.31460000e-02,
        5.38502000e-02, 7.14264349e+01, 2.71444855e-01, 5.81242444e-01,
        7.56170040e-02, 8.87041519e-01, 1.28400354e+00, 1.31849039e+00],
       [3.00000000e+00, 1.00000000e+00, 5.95130770e-02, 1.93380000e-02,
        4.46416000e-02, 7.01562907e+01, 2.03530770e-01, 6.00759218e-01,
        5.28287400e-03, 8.89399386e-01, 1.33827612e+00, 1.35493296e+00],
       [1.00000000e+00, 0.00000000e+00, 7.39416080e-02, 2.47160000e-02,
        5.64374000e-02, 7.58635749e+01, 2.61360087e-01, 6.25216415e-01,
        3.05179610e-02, 8.75984295e-01, 1.55501317e+00, 1.48413830e+00],
       [2.00000000e+00, 0.00000000e+00, 5.83104400e-02, 1.31190000e-02,
        3.10142400e-02, 8.20834919e+01, 2.22069281e-01, 6.02

In [11]:
cell_df['Status'] = cell_df['Status'].astype('int')
y = np.asarray(cell_df['Status'])
y [0:5]

array([0, 0, 0, 0, 0])

In [12]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (192, 12) (192,)
Test set: (48, 12) (48,)


In [34]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [35]:
yhat = clf.predict(X_test)
yhat [0:5]

array([1, 0, 0, 0, 0])

In [36]:
from sklearn.metrics import classification_report, confusion_matrix
import itertools

In [37]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In [38]:
from sklearn.metrics import f1_score
f1_score(y_test, yhat, average='weighted') 

0.813235294117647

In [39]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, yhat)

E:\digitalent2\EDA\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.8125